#!/usr/bin/env node
/**
 * One-shot local dev for the test chat UI.
 *
 *   npm run dev:chat
 *
 * Does three things so you never hardcode a deployment URL again:
 *   1. Reads CONVEX_URL from the root .env.local (the deployment the Convex
 *      CLI actually targets) and writes it to web/convex-config.js, which the
 *      chat page reads at load — so the UI always points at the active dev
 *      deployment automatically.
 *   2. Serves web/ on http://localhost:3000 and opens the chat page.
 *   3. Runs `npx convex dev` in the foreground (wakes a paused deployment,
 *      pushes testChat, streams logs). Ctrl-C stops everything.
 */
import { spawn } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createServer } from "node:http";
import { extname, join, normalize } from "node:path";

const PORT = 3000;
const WEB_DIR = new URL("../web/", import.meta.url).pathname;
const PAGE = "/test-chat.html";

// ── 1. Resolve the active deployment URL from .env.local ──────────────────
function readConvexUrl() {
  if (!existsSync(".env.local")) return "";
  const env = readFileSync(".env.local", "utf8");
  const m = env.match(/^\s*CONVEX_URL\s*=\s*(.+?)\s*$/m);
  return m ? m[1].trim() : "";
}
const convexUrl = readConvexUrl();
if (!convexUrl) {
  console.error("⚠️  Could not find CONVEX_URL in .env.local — the chat page will fall back to its built-in default.");
} else {
  console.log(`→ Test chat will connect to ${convexUrl}`);
}
writeFileSync(
  join(WEB_DIR, "convex-config.js"),
  `// Generated by scripts/dev-chat.mjs — do not edit.\nwindow.CONVEX_URL = ${JSON.stringify(convexUrl)};\n`,
);

// ── 2. Static file server for web/ ────────────────────────────────────────
const MIME = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".png": "image/png", ".svg": "image/svg+xml" };
const server = createServer((req, res) => {
  const urlPath = decodeURIComponent((req.url || "/").split("?")[0]);
  const rel = normalize(urlPath === "/" ? PAGE : urlPath).replace(/^(\.\.[/\\])+/, "");
  let file = join(WEB_DIR, rel);
  // Resolve extensionless routes like /test-chat → /test-chat.html so you don't
  // have to type the extension.
  if (!existsSync(file) && !extname(file) && existsSync(file + ".html")) {
    file += ".html";
  }
  if (!file.startsWith(WEB_DIR) || !existsSync(file)) {
    res.writeHead(404).end("Not found");
    return;
  }
  res.writeHead(200, { "Content-Type": MIME[extname(file)] || "application/octet-stream" });
  res.end(readFileSync(file));
});

// Try PORT, then the next few ports if something else (e.g. a stray `next dev`)
// already holds it — binding silently to a busy port is what made the browser
// land on the wrong server and show "Not found".
let port = PORT;
server.on("error", (err) => {
  if (err.code === "EADDRINUSE" && port < PORT + 10) {
    console.warn(`⚠️  Port ${port} is busy — trying ${port + 1}…`);
    port += 1;
    setTimeout(() => server.listen(port), 100);
  } else {
    console.error(`Could not start the chat server: ${err.message}`);
    process.exit(1);
  }
});
server.listen(port, () => {
  const url = `http://localhost:${port}${PAGE}`;
  console.log(`→ Test chat UI: ${url}`);
  const opener = process.platform === "darwin" ? "open" : process.platform === "win32" ? "start" : "xdg-open";
  spawn(opener, [url], { stdio: "ignore", detached: true, shell: process.platform === "win32" }).unref();
});

// ── 3. Run convex dev in the foreground ───────────────────────────────────
const convex = spawn("npx", ["convex", "dev"], { stdio: "inherit", shell: false });
const stop = () => { convex.kill("SIGINT"); process.exit(0); };
process.on("SIGINT", stop);
process.on("SIGTERM", stop);
convex.on("exit", (code) => process.exit(code ?? 0));
